name: Artifact
on: 
  workflow_dispatch:
jobs:
  uploading-the-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "creating a file"
        run: echo " hi this is my artifact file " >> myfile.txt

      - name: " viewing the file"
        run:  cat myfile.txt
        
      - name: " uploading the file "
        uses:  actions/upload-artifact@v7.0.1
        with:
          name: artifact.txt
          path:  myfile.txt
    
  downloading-the-artifact:
    needs: uploading-the-artifact
    runs-on: ubuntu-latest
    steps:
      - name:  " Downloading the artifact "
        uses:  actions/download-artifact@v3.1.0
        with:  
          name:  artifact.txt    
      - name:  " viewing the downloaded file "
        run:  cat artifact.txt
