name:  3rd-pratice
on:
  workflow_dispatch:
jobs:
  '3rd-pratice'
    runs-on:  ubutnu-latest
    steps:
      -  name: '1st checking the work-dispacth command'
         run:  ls -la
         
      -  name: 'checking the inside directory'
         run: |
           echo "this is my txt" >> file.txt
           echo "this is my second file" >>file.txt
           cat file.txt
    
