name:  6th-pratice
on: 
  workflow_dispatch: 
jobs:
  first-pratice:
    runs-on: ubuntu-22.04
    steps:
      - name:  1
        run:  |
            pwd
            echo " this is " whoami
            ls -l
  second-pratice:  
    runs-on: ubuntu-22.04
    steps:
      - name:  2
        run:  |
            pwd
            echo " this is " whoami
            ls -l
