name: Environment-variable
on: 
  workflow_dispatch: 
env:
  NAME:  Jebarson
jobs:
  first-Environment:  
    runs-on:  ubuntu-latest
    steps:
      - name: "Checking the env"
        run:  |
          echo "this is $NAME"
          ls -l
          uname -a
