name:  types of triggers
on:  
  push:
  pull_request:
    branches:
      -  main
#  schedule:
 #   -  cron:  " * * * * * "
 workflow_dispatch:
   inputs:
     environment:
       description:  " choose descrioption "
       required:  true
       default:  "developeer"
jobs:
    triggers:
      runs-on: ubuntu-latest
      steps:
        -  name: checkinng the trigger
           run:  echo " push trigger successful"
           
    
             

